services:
  frontend:
    container_name: frontend-react
    build:
      context: ./frontend-react
      dockerfile: docker/dev.Dockerfile

    environment:
      WATCHPACK_POLLING: true
    init: true
    env_file:
      - .env
      - .env.dev.local
    volumes:
      - ./frontend-react/src:/app/src
      - ./frontend-react/public:/app/public
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - app_network
    # depends_on:
      # backend:
        # condition: service_healthy
    
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: docker/devPure.Dockerfile
    env_file:
        - .env
        - .env.dev.local
    ports:
      - 8081:8081
    volumes:
      - ./api/app:/app/app
      - ./api/requirements.txt:/app/requirements.txt
    environment:
      - WATCHFILES_FORCE_POLLING=1  # This forces file watching (solves issues with hot reloading on windows)
      - WATCHFILES_POLLING_INTERVAL=1  # Check every 1 second
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/app

      # ✅ GPU environment variables
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # ✅ Force TensorFlow to use GPU
      - CUDA_VISIBLE_DEVICES=0
    networks:
      - app_network
    # depends_on:
      # backend:
        # condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    # restart: unless-stopped
      
  # db:
  #   container_name: db
  #   image: 'postgres:17'
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #     - .env.dev.local
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 10s
  #     retries: 10
  #     timeout: 5s
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - "pgdata:/var/lib/postgresql/data"
  #   networks:
  #     - app_network

  # redis:
  #   container_name: redis
  #   image: redis:8.0-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   env_file:
  #    - .env
  #    - .env.dev.local
  #   command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
  #   networks:
  #     - app_network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 5s  

volumes:
  pgdata:
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge
